Walkhub/walkhub_android

presentation/src/main/AndroidManifest.xml
presentation/src/main/java/com/semicolon/walkhub/ui/MainActivity.kt
presentation/src/main/res/layout/activity_main.xml

> 패키지 구조를 설계합니다
- domain 모듈 구조 설계
- data 모듈 구조 설계
- presentation 모듈 구조 설계

🔀 :: (#1) set package structure

---

data/src/main/java/com/semicolon/data/remote/api/ExerciseApi.kt
data/src/main/java/com/semicolon/data/remote/datasource/RemoteExerciseDataSource.kt
data/src/main/java/com/semicolon/data/remote/datasource/RemoteExerciseDataSourceImpl.kt
data/src/main/java/com/semicolon/data/remote/request/exercise/FinishMeasureExerciseRequest.kt
data/src/main/java/com/semicolon/data/remote/request/exercise/SaveDailyExerciseRequest.kt
data/src/main/java/com/semicolon/data/remote/request/exercise/SendLocationRecordsRequest.kt
data/src/main/java/com/semicolon/data/remote/request/exercise/StartMeasureExerciseRequest.kt
data/src/main/java/com/semicolon/data/remote/response/exercise/ExerciseIdResponse.kt
data/src/main/java/com/semicolon/data/util/HttpHandler.kt
domain/src/main/java/com/semicolon/domain/exception/basic/BadRequestException.kt
domain/src/main/java/com/semicolon/domain/exception/basic/ConflictException.kt
domain/src/main/java/com/semicolon/domain/exception/basic/ForbiddenException.kt
domain/src/main/java/com/semicolon/domain/exception/basic/NoInternetException.kt
domain/src/main/java/com/semicolon/domain/exception/basic/NotFoundException.kt
domain/src/main/java/com/semicolon/domain/exception/basic/ServerException.kt
domain/src/main/java/com/semicolon/domain/exception/basic/TimeoutException.kt
domain/src/main/java/com/semicolon/domain/exception/basic/UnauthorizedException.kt
domain/src/main/java/com/semicolon/domain/exception/basic/UnknownException.kt

> 운동 관련 비즈니스 로직 중 네트워크 통신을 하는 부분을 구현했습니다.
- dto class
- retrofit service
- data source
- http handler

🔀 :: (#27) exercise network logic

---

data/src/main/java/com/semicolon/data/local/database/WalkHubDataBase.kt

빌드시 데이터베이스부분에서 오류나는걸 수정
* walkHubDatabase 파일 수정(entity 기입)
-

🔀 :: (#39) database error fix

---

data/src/main/java/com/semicolon/data/remote/datasource/RemoteRankDataSource.kt
data/src/main/java/com/semicolon/data/remote/datasource/RemoteRankDataSourceImpl.kt

> 
datasource ,datasourceImpl
Rank부분의 datasource 와 datasourceImpl을 작성한다.

🔀 :: (#31)  Rank부분  datasource & datasourceImpl

---

data/src/main/java/com/semicolon/data/remote/api/SchoolApi.kt
data/src/main/java/com/semicolon/data/remote/response/school/SearchSchoolResponse.kt

- school api, entity
- search school api, entity 개발

🔀 :: (#41) school api, entity 작성

---

buildSrc/src/main/kotlin/Dependency.kt
buildSrc/src/main/kotlin/Version.kt
data/build.gradle.kts
data/src/main/java/com/semicolon/data/background/task/ExerciseBackgroundTask.kt
data/src/main/java/com/semicolon/data/background/task/ExerciseBackgroundTaskImpl.kt
data/src/main/java/com/semicolon/data/background/worker/SynchronizeExerciseWorker.kt
presentation/build.gradle.kts
presentation/src/main/AndroidManifest.xml
presentation/src/main/java/com/semicolon/walkhub/di/WalkHubApplication.kt

> 운동 기록 동기화 코드 맹글었습니다
-  work manager를 이용해 코드 작성

🔀 :: (#48) exercise synchronization

---

data/src/main/java/com/semicolon/data/remote/datasource/RemoteChallengeDateSource.kt
data/src/main/java/com/semicolon/data/remote/datasource/RemoteChallengeDateSourceImpl.kt
data/src/main/java/com/semicolon/data/repository/ChallengeRepositoryImpl.kt

> 
* challenge remote datasource에 HttpHandler가 사용되고있지 않았음
- 
* challenge remote datasource에 HttpHandler 사용 및 remote datasource의 반환값을 response로 변경
-

🔀 :: (#53) challenge remote datasource HttpHandler 사용

---

buildSrc/src/main/kotlin/Dependency.kt
buildSrc/src/main/kotlin/Version.kt
data/build.gradle.kts
data/src/main/java/com/semicolon/data/local/datasource/LocalExerciseDataSource.kt
data/src/main/java/com/semicolon/data/local/datasource/LocalExerciseDataSourceImpl.kt
data/src/main/java/com/semicolon/data/local/entity/exercise/WalkRecordEntity.kt
data/src/main/java/com/semicolon/data/local/storage/ExerciseInfoDataStorage.kt
data/src/main/java/com/semicolon/data/local/storage/ExerciseInfoDataStorageImpl.kt
data/src/main/java/com/semicolon/data/remote/request/exercise/FinishMeasureExerciseRequest.kt
data/src/main/java/com/semicolon/data/remote/request/exercise/SendLocationRecordsRequest.kt
data/src/main/java/com/semicolon/data/remote/request/exercise/StartMeasureExerciseRequest.kt
data/src/main/java/com/semicolon/data/repository/ExerciseRepositoryImpl.kt
data/src/main/java/com/semicolon/data/util/UtilFunc.kt
domain/src/main/java/com/semicolon/domain/enum/GoalType.kt

> ExerciseRepository와 이것을 구현하는데 필요한 각종 기능을 개발했습니다.
- ExerciseRepository 구현
- LocalExerciseDataSource 수정
- 각종 확장함수 추가

🔀 :: (#55) exercise repository implementation

---

domain/src/main/java/com/semicolon/domain/entity/users/FindUserAccountEntity.kt
domain/src/main/java/com/semicolon/domain/param/user/PatchUserHealthParam.kt
domain/src/main/java/com/semicolon/domain/param/user/SignUpClassParam.kt
domain/src/main/java/com/semicolon/domain/param/user/UpdateProfileParam.kt
domain/src/main/java/com/semicolon/domain/repository/UserRepository.kt
domain/src/main/java/com/semicolon/domain/usecase/user/FetchMypageUseCase.kt
domain/src/main/java/com/semicolon/domain/usecase/user/FetchUserOwnBadgeUseCase.kt
domain/src/main/java/com/semicolon/domain/usecase/user/FetchUserProfileUseCase.kt
domain/src/main/java/com/semicolon/domain/usecase/user/FindUserAccountUseCase.kt
domain/src/main/java/com/semicolon/domain/usecase/user/PatchSchoolUseCase.kt
domain/src/main/java/com/semicolon/domain/usecase/user/PatchUserChangePasswordUseCase.kt
domain/src/main/java/com/semicolon/domain/usecase/user/PatchUserHealthUseCase.kt
domain/src/main/java/com/semicolon/domain/usecase/user/PostUserSignInUseCase.kt
domain/src/main/java/com/semicolon/domain/usecase/user/PostUserSignUpUseCase.kt
domain/src/main/java/com/semicolon/domain/usecase/user/SetBadgeUseCase.kt
domain/src/main/java/com/semicolon/domain/usecase/user/SignUpClassUseCase.kt
domain/src/main/java/com/semicolon/domain/usecase/user/UpdateProfileUseCase.kt
domain/src/main/java/com/semicolon/domain/usecase/user/VerifyUserPhoneNumberUseCase.kt

user의 두번째 domain 구현입니다.
usecase,
param,
entity,
작업 했습니다.

🔀 :: (#57) User Domain 구현 2

---

data/src/main/java/com/semicolon/data/remote/api/UserApi.kt
data/src/main/java/com/semicolon/data/remote/datasource/RemoteUserDataSource.kt
data/src/main/java/com/semicolon/data/remote/datasource/RemoteUserDataSourceImpl.kt
data/src/main/java/com/semicolon/data/remote/request/users/PatchUserHealthRequest.kt
data/src/main/java/com/semicolon/data/remote/request/users/SignUpClassRequest.kt
data/src/main/java/com/semicolon/data/remote/response/users/FindUserAccountResponse.kt
data/src/main/java/com/semicolon/data/repository/UserRepositoryImpl.kt
domain/src/main/java/com/semicolon/domain/param/user/SignUpClassParam.kt

🔀 :: (#66) user data 로직 2

---

data/src/main/java/com/semicolon/data/remote/datasource/RemoteSchoolDataSource.kt
data/src/main/java/com/semicolon/data/remote/datasource/RemoteSchoolDataSourceImpl.kt
data/src/main/java/com/semicolon/data/remote/response/school/SearchSchoolResponse.kt
data/src/main/java/com/semicolon/data/repository/SchoolRepositoryImpl.kt
domain/src/main/java/com/semicolon/domain/entity/school/SearchSchoolEntity.kt
domain/src/main/java/com/semicolon/domain/repository/SchoolRepository.kt
domain/src/main/java/com/semicolon/domain/usecase/school/SearchSchoolUseCase.kt

-school 관련 logic
- remote school datasource,  remote school repository, search school use case
- api 명세 변경에 따른 search school response 수정

🔀 :: (#58) school logic

---

domain/src/main/java/com/semicolon/domain/entity/notification/NotificationEntity.kt
domain/src/main/java/com/semicolon/domain/entity/notification/NotificationListEntity.kt
domain/src/main/java/com/semicolon/domain/repository/NotificationRepository.kt
domain/src/main/java/com/semicolon/domain/usecase/notification/FetchNotificationListUseCase.kt
domain/src/main/java/com/semicolon/domain/usecase/notification/PatchNotificationIsReadUseCase.kt
domain/src/main/java/com/semicolon/domain/usecase/notification/ReadNotificationUseCase.kt

notification domain 모듈에 관한 로직을 구현한다
- 
-

🔀 :: (#52) notification domain 로직 구현

---

presentation/src/main/java/com/semicolon/walkhub/ui/base/BaseActivity.kt
presentation/src/main/java/com/semicolon/walkhub/ui/base/BaseFragment.kt

🔀 :: (#72) base

---

presentation/src/main/res/values/colors.xml

🔀 :: (#84) colors

---

data/src/main/java/com/semicolon/data/remote/api/ChallengeApi.kt
data/src/main/java/com/semicolon/data/remote/datasource/RemoteChallengeDateSource.kt
data/src/main/java/com/semicolon/data/remote/datasource/RemoteChallengeDateSourceImpl.kt
data/src/main/java/com/semicolon/data/repository/ChallengeRepositoryImpl.kt
domain/src/main/java/com/semicolon/domain/repository/ChallengeRepository.kt
domain/src/main/java/com/semicolon/domain/usecase/challenge/FetchMyChallengesUseCase.kt

🔀 :: (#81) 참여한 챌린지 목록보기

---

data/src/main/java/com/semicolon/data/background/worker/SynchronizeExerciseWorker.kt
data/src/main/java/com/semicolon/data/remote/api/ExerciseApi.kt
data/src/main/java/com/semicolon/data/remote/datasource/RemoteExerciseDataSource.kt
data/src/main/java/com/semicolon/data/remote/datasource/RemoteExerciseDataSourceImpl.kt
data/src/main/java/com/semicolon/data/remote/request/exercise/SaveDailyExerciseRequest.kt
data/src/main/java/com/semicolon/data/remote/response/exercise/ExerciseAnalysisResultResponse.kt
data/src/main/java/com/semicolon/data/remote/response/exercise/ExerciseRecordListResponse.kt
data/src/main/java/com/semicolon/data/repository/ExerciseRepositoryImpl.kt
domain/src/main/java/com/semicolon/domain/entity/exercise/ExerciseAnalysisResultEntity.kt
domain/src/main/java/com/semicolon/domain/entity/exercise/ExerciseRecordEntity.kt
domain/src/main/java/com/semicolon/domain/repository/ExerciseRepository.kt
domain/src/main/java/com/semicolon/domain/usecase/exercise/FetchDailyExerciseRecordUseCase.kt
domain/src/main/java/com/semicolon/domain/usecase/exercise/FetchExerciseAnalysisResultUseCase.kt
domain/src/main/java/com/semicolon/domain/usecase/exercise/FetchExerciseRecordListUseCase.kt
domain/src/main/java/com/semicolon/domain/usecase/exercise/FinishMeasureExerciseUseCase.kt
domain/src/main/java/com/semicolon/domain/usecase/exercise/IsMeasuringUseCase.kt
domain/src/main/java/com/semicolon/domain/usecase/exercise/StartMeasureExerciseUseCase.kt
domain/src/main/java/com/semicolon/domain/usecase/exercise/StartRecordExerciseUseCase.kt

> 운동관련 비즈니스 로직에 변화가 있어서 반영했습니다.
- 운동 기록 리스트 api
- 운동 분석 결과 api

🔀 :: (#86) changes in exercise

---

buildSrc/src/main/kotlin/Dependency.kt
buildSrc/src/main/kotlin/Version.kt
data/build.gradle.kts
domain/build.gradle.kts

Mockito kotlin setting import 
- 
-

🔀 :: (#89) mockito kotlin setting 설정

---

data/src/main/java/com/semicolon/data/remote/datasource/RemoteChallengeDateSource.kt
data/src/main/java/com/semicolon/data/remote/datasource/RemoteChallengeDateSourceImpl.kt
data/src/main/java/com/semicolon/data/repository/ChallengeRepositoryImpl.kt

toEntity()의 위치를 datasource로 통일시켰습니다.
- 
-

🔀 :: challenge repository toEntity 통일

---

data/src/test/java/com/semicolon/data/datasource/RemoteSchoolDataSourceTest.kt

remote school data source test 구현
- 
-

🔀 :: (#97) remote school data source test

---

data/src/test/java/com/semicolon/data/repository/ChallengeRepositoryUnitTest.kt

challenge repository를 테스트 하였습니다.
- 
-

🔀 :: (#93) test challenge repository

---

data/src/test/java/com/semicolon/data/datasource/LocalChallengeDataSourceUnitTest.kt

Local challenge datasource를 테스트 하였습니다
- 
-

🔀 :: (#99) LocalChallengeDataSource test

---

domain/src/test/java/com/semicolon/domain/usecase/challenge/FetchChallengeDetailUseCaseUnitTest.kt
domain/src/test/java/com/semicolon/domain/usecase/challenge/FetchChallengeParticipantsUseCaseUnitTest.kt
domain/src/test/java/com/semicolon/domain/usecase/challenge/FetchChallengesUseCaseUnitTest.kt
domain/src/test/java/com/semicolon/domain/usecase/challenge/FetchMyChallengesUseCaseUnitCase.kt
domain/src/test/java/com/semicolon/domain/usecase/challenge/PostParticipateChallengeUseCaseUnitTest.kt

challenge usecase들을 테스트 하였습니다.
- 
-

🔀 :: (#94) test challenge usecase

---

domain/src/test/java/com/semicolon/domain/usecase/school/SearchSchoolUseCaseUnitTest.kt

search school use case unit test code 작성
- 
-

🔀 :: (#112) search school use case unit test

---

data/src/test/java/com/semicolon/data/datasource/LocalUserDataSourceUnitTest.kt
data/src/test/java/com/semicolon/data/datasource/RemoteUserDataSourceUnitTest.kt

user datasource를 테스트 하였습니다.
- 
-

🔀 :: (#111) user data source test

---

data/src/main/java/com/semicolon/data/local/converter/TypeConverters.kt
data/src/main/java/com/semicolon/data/local/dao/BadgeDao.kt
data/src/main/java/com/semicolon/data/local/database/WalkHubDataBase.kt
data/src/main/java/com/semicolon/data/local/datasource/LocalBadgeDataSource.kt
data/src/main/java/com/semicolon/data/local/datasource/LocalBadgeDataSourceImpl.kt
data/src/main/java/com/semicolon/data/local/entity/badge/FetchMyBadgesRoomEntity.kt
data/src/main/java/com/semicolon/data/local/entity/badge/FetchNewBadgesRoomEntity.kt
data/src/main/java/com/semicolon/data/local/entity/badge/FetchUserBadgesRoomEntity.kt
data/src/main/java/com/semicolon/data/remote/api/BadgeApi.kt
data/src/main/java/com/semicolon/data/remote/api/UserApi.kt
data/src/main/java/com/semicolon/data/remote/datasource/RemoteBadgeDataSource.kt
data/src/main/java/com/semicolon/data/remote/datasource/RemoteBadgeDataSourceImpl.kt
data/src/main/java/com/semicolon/data/remote/response/badge/FetchMyBadgesResponse.kt
data/src/main/java/com/semicolon/data/remote/response/badge/FetchNewBadgesResponse.kt
data/src/main/java/com/semicolon/data/remote/response/badge/FetchUserBadgesResponse.kt
data/src/main/java/com/semicolon/data/repository/BadgeRepositoryImpl.kt
domain/src/main/java/com/semicolon/domain/entity/badge/FetchMyBadgesEntity.kt
domain/src/main/java/com/semicolon/domain/entity/badge/FetchNewBadgesEntity.kt
domain/src/main/java/com/semicolon/domain/entity/badge/FetchUserBadgesEntity.kt
domain/src/main/java/com/semicolon/domain/repository/BadgeRepository.kt
domain/src/main/java/com/semicolon/domain/usecase/badge/FetchMyBadgesUseCase.kt
domain/src/main/java/com/semicolon/domain/usecase/badge/FetchNewBadgesUseCase.kt
domain/src/main/java/com/semicolon/domain/usecase/badge/FetchUserBadgesUseCase.kt

badge 로직 구현
(양이 얼마 없어 domain까지 했습니다..)

🔀 :: (#107) badge 구현

---

data/src/main/java/com/semicolon/data/remote/datasource/RemoteUserDataSource.kt
data/src/main/java/com/semicolon/data/remote/datasource/RemoteUserDataSourceImpl.kt
data/src/main/java/com/semicolon/data/repository/UserRepositoryImpl.kt
data/src/test/java/com/semicolon/data/datasource/RemoteUserDataSourceUnitTest.kt

user repository에 있는 toEntity를 datasource에서 처리함
- 
-

🔀 :: (#126) user toEntity datasource

---

buildSrc/src/main/kotlin/Dependency.kt
buildSrc/src/main/kotlin/Version.kt
presentation/build.gradle.kts
presentation/src/main/AndroidManifest.xml
presentation/src/main/java/com/semicolon/walkhub/di/WalkHubApplication.kt
presentation/src/main/java/com/semicolon/walkhub/ui/login/LoginActivity.kt
presentation/src/main/res/layout/activity_login.xml

> 구글 OAuth와 연동하는 코드와 퍼미션을 받아오는 코드 작성
- 개요와 같음

🔀 :: (#133) google oauth and permission

---

buildSrc/src/main/kotlin/Dependency.kt
data/build.gradle.kts
data/src/main/java/com/semicolon/data/repository/ExerciseRepositoryImpl.kt
data/src/test/java/com/semicolon/data/repository/ExerciseRepositoryUnitTest.kt
domain/src/test/java/com/semicolon/domain/usecase/exercise/FetchDailyExerciseRecordUseCaseTest.kt
domain/src/test/java/com/semicolon/domain/usecase/exercise/FetchExerciseAnalysisResultUseCaseTest.kt
domain/src/test/java/com/semicolon/domain/usecase/exercise/FetchExerciseRecordListUseCaseTest.kt
domain/src/test/java/com/semicolon/domain/usecase/exercise/FinishMeasureExerciseUseCaseTest.kt
domain/src/test/java/com/semicolon/domain/usecase/exercise/IsMeasuringUseCaseTest.kt
domain/src/test/java/com/semicolon/domain/usecase/exercise/StartMeasureExerciseUseCaseTest.kt
domain/src/test/java/com/semicolon/domain/usecase/exercise/StartRecordExerciseUseCaseTest.kt

> 운동관련 비즈니스 로직 중 도메인(usecase, repository)에 대한 테스트 코드를 작성헀습니다
- 테스트코드 작성
- 발견한 오류 수정
- ExerciseRepository에서 운동 기록 리스트와 운동 분석 결과를 가져올 때 데이터를 제대로 발행하도록 수정했습니다.

🔀 :: (#105) test exercise domain

---

presentation/src/main/res/values-night/styles.xml
presentation/src/main/res/values/themes.xml

🔀 :: (#138) set fonts & style

---

data/src/test/java/com/semicolon/data/repository/UserRepositoryUnitTest.kt

user repository 테스트코드를 작성하였습니다
- 
-

🔀 :: (#115) user repository test

---

presentation/src/main/java/com/semicolon/walkhub/di/NetWorkModule.kt

hilt net work module을 만들었다.
- 
-

🔀 :: (#78) network_module

---

presentation/src/main/java/com/semicolon/walkhub/di/RoomModule.kt

🔀 :: (#150) room module

---

data/src/main/java/com/semicolon/data/remote/api/NotificationApi.kt

🔀 :: (#164) notice URL / 제거

---

data/src/main/java/com/semicolon/data/remote/api/NoticesApi.kt

🔀 :: (#163) notification URL / 제거

---

data/src/main/java/com/semicolon/data/local/database/WalkHubDataBase.kt
domain/src/main/java/com/semicolon/domain/entity/notice/NoticeEntity.kt

🔀 :: (#167) 병합 오류 수정

---

presentation/src/main/java/com/semicolon/walkhub/di/RoomModule.kt

🔀 :: (#160) add Room Dao

---

data/src/main/java/com/semicolon/data/remote/api/RankApi.kt

> Rank interface url에서 /삭제
- Rank interface url에서 /를 삭제했습니다.

🔀 :: (#169)  Rank interface url에서 /삭제

---

presentation/src/main/java/com/semicolon/walkhub/di/LocalDataSourceModule.kt
presentation/src/main/java/com/semicolon/walkhub/di/RemoteDataSourceModule.kt
presentation/src/main/java/com/semicolon/walkhub/di/RoomModule.kt

local, remote datasource module 작성
- 
-

🔀 :: (#172) datasource module

---

presentation/src/main/java/com/semicolon/walkhub/di/RepositoryModule.kt

🔀:: (#178) repository module

---

presentation/src/main/java/com/semicolon/walkhub/di/StorageModule.kt

🔀:: (#181) storage module

---

presentation/src/main/java/com/semicolon/walkhub/ui/MainActivity.kt
presentation/src/main/java/com/semicolon/walkhub/ui/base/BaseActivity.kt
presentation/src/main/java/com/semicolon/walkhub/ui/base/BaseFragment.kt
presentation/src/main/java/com/semicolon/walkhub/ui/challenge/ChallengeFragment.kt
presentation/src/main/java/com/semicolon/walkhub/ui/home/HomeFragment.kt
presentation/src/main/java/com/semicolon/walkhub/ui/hub/adapter/HubSchoolRankRvAdapter.kt
presentation/src/main/java/com/semicolon/walkhub/ui/hub/model/HubSchoolRank.kt
presentation/src/main/java/com/semicolon/walkhub/ui/hub/ui/HubFragment.kt
presentation/src/main/java/com/semicolon/walkhub/ui/login/LoginActivity.kt
presentation/src/main/java/com/semicolon/walkhub/ui/profile/ProfileFragment.kt
presentation/src/main/java/com/semicolon/walkhub/viewmodel/HubMainViewModel.kt
presentation/src/main/res/layout/fragment_hub.xml
presentation/src/main/res/layout/hub_school_rank_view.xml
presentation/src/main/res/layout/item_hub_main_spinner.xml
presentation/src/main/res/values/array.xml

spinner 작성
base 수정
hub viewmodel (fake data)
hub fragment 완성

🔀 :: (#185) hub main logic

---

data/src/main/java/com/semicolon/data/remote/api/RankApi.kt
data/src/main/java/com/semicolon/data/remote/datasource/RemoteRankDataSource.kt
data/src/main/java/com/semicolon/data/remote/datasource/RemoteRankDataSourceImpl.kt
data/src/main/java/com/semicolon/data/repository/RankRepositoryImpl.kt
domain/src/main/java/com/semicolon/domain/param/rank/FetchUserRankParam.kt

> 유저랭킹조회 부분을 수정한다.
- 바뀐 명세에 따라 변경해줍니다!
- RanlRepositoryImpl, FetchUserRankParam, RemoteRankDataSource, RemoteRankDataSourceImpl, RankApi

🔀 :: (#191) 유저랭킹조회 수정

---

data/src/main/java/com/semicolon/data/remote/datasource/RemoteBadgeDataSource.kt
data/src/main/java/com/semicolon/data/remote/datasource/RemoteBadgeDataSourceImpl.kt
data/src/main/java/com/semicolon/data/repository/BadgeRepositoryImpl.kt
data/src/test/java/com/semicolon/data/datasource/RemoteBadgeDataSourceUnitTest.kt

badge remote datasource test code 추가
- 
-

🔀:: (#155) badge remote datasource test

---

presentation/src/main/AndroidManifest.xml
presentation/src/main/java/com/semicolon/walkhub/ui/hub/adapter/HubSchoolRankRvAdapter.kt
presentation/src/main/java/com/semicolon/walkhub/ui/hub/adapter/HubSearchUserRvAdapter.kt
presentation/src/main/java/com/semicolon/walkhub/ui/hub/adapter/HubViewPagerAdapter.kt
presentation/src/main/java/com/semicolon/walkhub/ui/hub/model/OurSchoolUserRankData.kt
presentation/src/main/java/com/semicolon/walkhub/ui/hub/model/UserRankData.kt
presentation/src/main/java/com/semicolon/walkhub/ui/hub/model/UserRankRvData.kt
presentation/src/main/java/com/semicolon/walkhub/ui/hub/ui/HubFragment.kt
presentation/src/main/java/com/semicolon/walkhub/ui/hub/ui/HubInfoFragment.kt
presentation/src/main/java/com/semicolon/walkhub/ui/hub/ui/HubRankFragment.kt
presentation/src/main/java/com/semicolon/walkhub/ui/hub/ui/HubSchoolActivity.kt
presentation/src/main/java/com/semicolon/walkhub/viewmodel/hub/HubMainViewModel.kt
presentation/src/main/java/com/semicolon/walkhub/viewmodel/hub/HubUserRankViewModel.kt
presentation/src/main/res/layout/activity_hub_school.xml
presentation/src/main/res/layout/fragment_hub_info.xml
presentation/src/main/res/layout/fragment_hub_rank.xml
presentation/src/main/res/layout/hub_user_search_view.xml
presentation/src/main/res/menu/menu_hub_search.xml

🔀 :: (#190) hub school ui

---

data/src/test/java/com/semicolon/data/repository/BadgeRepositoryUnitTest.kt

🔀:: (#194) badge repository test

---

data/src/test/java/com/semicolon/data/datasource/LocalBadgeDataSourceUnitTest.kt

badge local datasource test
- 
-

🔀 :: (#144) badge local datasource test

---

domain/src/test/java/com/semicolon/domain/usecase/user/AutoLoginUseCaseUnitTest.kt
domain/src/test/java/com/semicolon/domain/usecase/user/FetchCaloriesLevelUseCaseUnitTest.kt
domain/src/test/java/com/semicolon/domain/usecase/user/FetchMyPageUseCaseUnitTest.kt
domain/src/test/java/com/semicolon/domain/usecase/user/FetchMypageUseCaseUnitTest.kt
domain/src/test/java/com/semicolon/domain/usecase/user/FetchUserProfileUseCaseUnitTest.kt
domain/src/test/java/com/semicolon/domain/usecase/user/FindUserAccountUseCaseUnitTest.kt
domain/src/test/java/com/semicolon/domain/usecase/user/PatchDailyWalkGoalUseCaseUnitTest.kt
domain/src/test/java/com/semicolon/domain/usecase/user/PatchSchoolUseCaseUnitTest.kt
domain/src/test/java/com/semicolon/domain/usecase/user/PatchUserChangePasswordUseCaseUnitTest.kt
domain/src/test/java/com/semicolon/domain/usecase/user/PatchUserHealthUseCaseUnitTest.kt
domain/src/test/java/com/semicolon/domain/usecase/user/PostUserSignInUseCaseUnitTest.kt
domain/src/test/java/com/semicolon/domain/usecase/user/PostUserSignUpUseCaseUnitTest.kt
domain/src/test/java/com/semicolon/domain/usecase/user/SignUpClassUseCaseUnitTest.kt
domain/src/test/java/com/semicolon/domain/usecase/user/UpdateProfileUseCaseUnitTest.kt
domain/src/test/java/com/semicolon/domain/usecase/user/VerifyUserPhoneNumberUseCaseUnitTest.kt

user usecase test code를 작성하였습니다
- 
-

🔀 :: (#143) user usecase test

---

presentation/src/main/java/com/semicolon/walkhub/bindingadapter/CircularProgressBarAdapter.kt
presentation/src/main/java/com/semicolon/walkhub/customview/CircularProgressBar.kt
presentation/src/main/res/layout/example_progress.xml

> circular progress bar
- circular progress bar 만들음

🔀 :: (#223) circular progress bar

---

presentation/src/main/java/com/semicolon/walkhub/ui/hub/adapter/HubSchoolRankRvAdapter.kt
presentation/src/main/java/com/semicolon/walkhub/ui/hub/model/HubSchoolRank.kt
presentation/src/main/java/com/semicolon/walkhub/ui/hub/ui/HubFragment.kt
presentation/src/main/java/com/semicolon/walkhub/ui/hub/ui/HubInfoFragment.kt
presentation/src/main/java/com/semicolon/walkhub/ui/hub/ui/HubRankFragment.kt
presentation/src/main/java/com/semicolon/walkhub/ui/hub/ui/HubSchoolActivity.kt
presentation/src/main/java/com/semicolon/walkhub/viewmodel/hub/HubMainViewModel.kt
presentation/src/main/java/com/semicolon/walkhub/viewmodel/hub/HubUserRankViewModel.kt
presentation/src/main/res/drawable-v24/bg_primary_button.xml
presentation/src/main/res/layout/activity_hub_school.xml
presentation/src/main/res/layout/fragment_hub_info.xml
presentation/src/main/res/layout/fragment_hub_rank.xml

hub fragment UI 및 코드 정리
(hub info fragment 디자인 미완성으로 인한 일부 미완)

🔀 :: (#196) hub fragment UI

---

domain/src/test/java/com/semicolon/domain/usecase/badge/FetchMyBadgesUseCaseUnitTest.kt
domain/src/test/java/com/semicolon/domain/usecase/badge/FetchNewBadgesUseCaseUnitTest.kt
domain/src/test/java/com/semicolon/domain/usecase/badge/FetchUserBadgesUseCaseUnitTest.kt
domain/src/test/java/com/semicolon/domain/usecase/badge/SetBadgeUseCaseUnitTest.kt

🔀:: (#209) badge usecase test

---

domain/src/main/java/com/semicolon/domain/entity/level/LevelEntity.kt
domain/src/main/java/com/semicolon/domain/repository/LevelRepository.kt
domain/src/main/java/com/semicolon/domain/usecase/level/FetchLevelListUseCase.kt
domain/src/main/java/com/semicolon/domain/usecase/level/PatchMaxLevelUseCase.kt

* Fetch level list use case
* Patch max level use case
* Level repository
- 
-

🔀 :: (#200) Level Domain

---

data/src/main/java/com/semicolon/data/local/dao/LevelDao.kt
data/src/main/java/com/semicolon/data/local/datasource/LocalLevelDataSource.kt
data/src/main/java/com/semicolon/data/local/datasource/LocalLevelDataSourceImpl.kt
data/src/main/java/com/semicolon/data/local/entity/level/LevelRoomEntity.kt
data/src/main/java/com/semicolon/data/remote/api/LevelApi.kt
data/src/main/java/com/semicolon/data/remote/datasource/RemoteLevelDataSource.kt
data/src/main/java/com/semicolon/data/remote/datasource/RemoteLevelDataSourceImpl.kt
data/src/main/java/com/semicolon/data/remote/response/level/LevelListResponse.kt
data/src/main/java/com/semicolon/data/repository/LevelRepositoryImpl.kt

* Level Data Layer를 제작하였습니다.
- 
-

🔀 :: (#233) Level Data

---

data/src/main/java/com/semicolon/data/interceptor/AuthorizationInterceptor.kt
presentation/src/main/java/com/semicolon/walkhub/di/NetWorkModule.kt

> 인증 인터셉터
- 인증 인터셉터 개발
- network 모듈에서 okhttp client를 만들 때 새로 만든 인터셉터를 추가하도록 변경

🔀 :: (#222) authorization interceptor

---

buildSrc/src/main/kotlin/Dependency.kt
presentation/src/main/java/com/semicolon/walkhub/di/NetWorkModule.kt
presentation/src/main/java/com/semicolon/walkhub/fcm/FCMManager.kt

> 이상한 코드 수정
- 빌드 안되는거 수정
- Hilt모듈 빠트린거 추가

🔀 :: (#239) strange code

---

data/src/main/java/com/semicolon/data/interceptor/AuthorizationInterceptor.kt

> 인증 인터셉터에서 토큰이 필요없는 api 제외
- 개요와 같음

🔀 :: (#252) add ignore cases in authorization interceptor

---

presentation/src/main/res/layout/fragment_profile.xml

🔀 :: (#245) 마이페이지 UI 구현

---

buildSrc/src/main/kotlin/Dependency.kt
buildSrc/src/main/kotlin/Version.kt
data/build.gradle.kts
data/src/main/java/com/semicolon/data/remote/datasource/RemoteSocketDataSource.kt
data/src/main/java/com/semicolon/data/remote/datasource/RemoteSocketDataSourceImpl.kt
data/src/main/java/com/semicolon/data/repository/SocketRepositoryImpl.kt
domain/src/main/java/com/semicolon/domain/repository/SocketRepository.kt
domain/src/main/java/com/semicolon/domain/usecase/socket/CheeringUseCase.kt
domain/src/main/java/com/semicolon/domain/usecase/socket/ConnectedSocketUseCase.kt
domain/src/main/java/com/semicolon/domain/usecase/socket/DisconnectedSocketUseCase.kt
presentation/build.gradle.kts
presentation/src/main/java/com/semicolon/walkhub/di/NetWorkModule.kt
presentation/src/main/java/com/semicolon/walkhub/di/RemoteDataSourceModule.kt
presentation/src/main/java/com/semicolon/walkhub/di/RepositoryModule.kt

처음에 scarlet 라이브러리를 쓰려 했지만 socket.io로 개발하였습니다.
socket 관련된 usecase 까지 한번에 하였습니다.
부득이 하게 socket 사용하는 사람이 손을 볼 수도 있을 겁니다!
-

🔀 :: (#220) socket

---

data/src/main/java/com/semicolon/data/local/dao/LocationRecordDao.kt
data/src/main/java/com/semicolon/data/local/database/WalkHubDataBase.kt
data/src/main/java/com/semicolon/data/local/datasource/LocalExerciseDataSource.kt
data/src/main/java/com/semicolon/data/local/datasource/LocalExerciseDataSourceImpl.kt
data/src/main/java/com/semicolon/data/local/entity/exercise/LocationRecordRoomEntity.kt
data/src/main/java/com/semicolon/data/local/storage/ExerciseInfoDataStorage.kt
data/src/main/java/com/semicolon/data/local/storage/ExerciseInfoDataStorageImpl.kt
data/src/main/java/com/semicolon/data/local/storage/FitnessAccumulateDataStorage.kt
data/src/main/java/com/semicolon/data/local/storage/FitnessAccumulateDataStorageImpl.kt
data/src/main/java/com/semicolon/data/local/storage/FitnessDataStorageImpl.kt
data/src/main/java/com/semicolon/data/local/storage/SpeedDataStorage.kt
data/src/main/java/com/semicolon/data/local/storage/SpeedDataStorageImpl.kt
data/src/main/java/com/semicolon/data/repository/ExerciseRepositoryImpl.kt
domain/src/main/java/com/semicolon/domain/entity/exercise/ExerciseEntity.kt
domain/src/main/java/com/semicolon/domain/entity/exercise/GoalEntity.kt
domain/src/main/java/com/semicolon/domain/enum/GoalType.kt
domain/src/main/java/com/semicolon/domain/enum/MeasuringState.kt
domain/src/main/java/com/semicolon/domain/repository/ExerciseRepository.kt
domain/src/main/java/com/semicolon/domain/usecase/exercise/FetchCurrentSpeedUseCase.kt
domain/src/main/java/com/semicolon/domain/usecase/exercise/FetchGoalUseCase.kt
domain/src/main/java/com/semicolon/domain/usecase/exercise/FetchMeasuredExerciseRecordUseCase.kt
domain/src/main/java/com/semicolon/domain/usecase/exercise/FetchMeasuredTimeUseCase.kt
domain/src/main/java/com/semicolon/domain/usecase/exercise/IsMeasuringUseCase.kt
domain/src/main/java/com/semicolon/domain/usecase/exercise/PauseMeasureExerciseUseCase.kt
domain/src/main/java/com/semicolon/domain/usecase/exercise/ResumeMeasureExerciseUseCase.kt
presentation/src/main/java/com/semicolon/walkhub/di/RoomModule.kt
presentation/src/main/java/com/semicolon/walkhub/di/StorageModule.kt

> 비즈니스 로직 추가
- 운동 측정 일시 중지, 재시작과 기타 등등

🔀 :: (#260) add exercise business logic

---

presentation/src/main/java/com/semicolon/walkhub/viewmodel/measure/MeasureHomeViewModel.kt

🔀 :: (#275)measure home viewmodel

---

data/src/main/java/com/semicolon/data/local/dao/LevelDao.kt
data/src/main/java/com/semicolon/data/local/database/WalkHubDataBase.kt
presentation/src/main/java/com/semicolon/walkhub/di/RoomModule.kt

level di 선언과 빌드 오류를 고쳤습니다.
- 
-

🔀 :: (#279) Level Di & error

---

presentation/src/main/java/com/semicolon/walkhub/adapter/BindingViewHolder.kt
presentation/src/main/java/com/semicolon/walkhub/adapter/RecyclerViewAdapter.kt
presentation/src/main/java/com/semicolon/walkhub/adapter/RecyclerViewItem.kt

* 공동으로 사용 가능한 recyclerview adapter를 만들었습니다.
- 
-

🔀 :: (#282) recycler view adapter

---

presentation/src/main/java/com/semicolon/walkhub/viewmodel/measure/MeasureViewModel.kt

🔀:: (#285) measure viewmodel

---

presentation/src/main/java/com/semicolon/walkhub/ui/profile/setting/SettingActivity.kt
presentation/src/main/res/layout/activity_setting.xml

> Fragment에서 SettingActivity로 변경

🔀 :: (#289) 프래그먼트에서 세팅 액티비티로 수정

---

presentation/src/main/java/com/semicolon/walkhub/ui/profile/setting/ModifyHealthInfoFragment.kt
presentation/src/main/res/drawable/girl_btn.xml
presentation/src/main/res/drawable/modify_health_edit_back.xml
presentation/src/main/res/layout/fragment_modify_health_info.xml

🔀 :: (#264) 건강정보 수정 UI 작성

---

data/src/main/java/com/semicolon/data/local/datasource/LocalExerciseDataSourceImpl.kt
presentation/src/main/AndroidManifest.xml
presentation/src/main/java/com/semicolon/walkhub/ui/analysis/ActivityAnalysis.kt
presentation/src/main/java/com/semicolon/walkhub/ui/analysis/ActivityAnalysisActivity.kt
presentation/src/main/java/com/semicolon/walkhub/ui/analysis/WalkGraph.kt
presentation/src/main/java/com/semicolon/walkhub/viewmodel/analysis/ActivityAnalysisViewModel.kt

> 활동 분석 view model
- view model 개발 & UI와 연동

🔀 :: (#232) activity analysis viewmodel

---

presentation/src/main/java/com/semicolon/walkhub/ui/analysis/ActivityAnalysis.kt
presentation/src/main/java/com/semicolon/walkhub/ui/analysis/AppBar.kt
presentation/src/main/java/com/semicolon/walkhub/ui/home/HomeFragment.kt
presentation/src/main/java/com/semicolon/walkhub/viewmodel/home/HomeViewModel.kt

🔀 :: (#297) connect main and analysis

---

presentation/src/main/java/com/semicolon/walkhub/ui/profile/setting/SettingActivity.kt
presentation/src/main/res/layout/activity_setting.xml

🔀 :: (#294) 세팅 뷰기능 추가

---

presentation/src/main/java/com/semicolon/walkhub/ui/profile/ProfileFragment.kt

🔀 :: (#291) 마이페이지 뷰기능 구현

---

data/src/main/java/com/semicolon/data/local/entity/rank/SchoolRankRoomEntity.kt
data/src/main/java/com/semicolon/data/remote/api/RankApi.kt
data/src/main/java/com/semicolon/data/remote/response/ranks/inquiryRank/school/SchoolRankResponse.kt
domain/src/main/java/com/semicolon/domain/entity/rank/SchoolRankEntity.kt
presentation/src/main/java/com/semicolon/walkhub/ui/hub/adapter/HubSearchSchoolRvAdapter.kt
presentation/src/main/java/com/semicolon/walkhub/ui/hub/model/HubSchoolRankData.kt
presentation/src/main/java/com/semicolon/walkhub/ui/hub/ui/HubRankFragment.kt
presentation/src/main/java/com/semicolon/walkhub/ui/hub/ui/HubSearchSchoolActivity.kt
presentation/src/main/java/com/semicolon/walkhub/viewmodel/hub/HubMainViewModel.kt
presentation/src/main/java/com/semicolon/walkhub/viewmodel/hub/HubSearchSchoolViewModel.kt
presentation/src/main/res/layout/activity_hub_search_school.xml
presentation/src/main/res/layout/fragment_hub.xml

🔀 :: (#300) hub viewmodel 구현 

---

data/src/main/java/com/semicolon/data/interceptor/AuthorizationInterceptor.kt
domain/src/main/java/com/semicolon/domain/exception/user/NeedLoginException.kt

> 토큰 재발급 Response가 변경되어서 반영했습니다
- 토큰 재발급 Response 클래스 변경
- 토큰 재발급 시 refresh token 갱신하는 코드 작성
- 토큰 재발급 실패시 throw 되는 예외 변경
- 토큰 재발급 실패시 `IOException` 의 서브 클래스를 던지도록 수정

🔀 :: (#314) change token logic & interceptor

---

presentation/src/main/java/com/semicolon/walkhub/ui/profile/setting/AccountInfoFragment.kt
presentation/src/main/res/layout/fragment_account_info.xml

🔀 :: (#262) 계정 정보 UI 구현

---

data/src/main/java/com/semicolon/data/remote/api/UserApi.kt
data/src/main/java/com/semicolon/data/remote/datasource/RemoteUserDataSource.kt
data/src/main/java/com/semicolon/data/remote/datasource/RemoteUserDataSourceImpl.kt
data/src/main/java/com/semicolon/data/remote/request/users/UpdateProfileRequest.kt
data/src/main/java/com/semicolon/data/remote/request/users/UserSignUpRequest.kt
data/src/main/java/com/semicolon/data/remote/request/users/VerifyPhoneNumberSignUpRequest.kt
data/src/main/java/com/semicolon/data/remote/response/users/FetchAuthInfoResponse.kt
data/src/main/java/com/semicolon/data/remote/response/users/FetchDailyGoalResponse.kt
data/src/main/java/com/semicolon/data/remote/response/users/FetchInfoResponse.kt
data/src/main/java/com/semicolon/data/remote/response/users/FetchMyPageResponse.kt
data/src/main/java/com/semicolon/data/remote/response/users/FetchUserHealthResponse.kt
data/src/main/java/com/semicolon/data/remote/response/users/FetchUserProfileResponse.kt
data/src/main/java/com/semicolon/data/remote/response/users/UserSignInResponse.kt
data/src/main/java/com/semicolon/data/remote/response/users/UserSignUpResponse.kt
data/src/main/java/com/semicolon/data/repository/UserRepositoryImpl.kt
domain/src/main/java/com/semicolon/domain/entity/users/UserMyPageEntity.kt
domain/src/main/java/com/semicolon/domain/param/user/PatchUserHealthParam.kt
domain/src/main/java/com/semicolon/domain/param/user/PostUserSignUpParam.kt
domain/src/main/java/com/semicolon/domain/param/user/SignUpClassParam.kt
domain/src/main/java/com/semicolon/domain/param/user/UpdateProfileParam.kt
domain/src/main/java/com/semicolon/domain/param/user/VerifyPhoneNumberSignUpParam.kt

> 
api 명세 업데이트에 따른 수정
+
새로 추가된 기능은 다른 이슈에서 작업

🔀 :: (#325) update users

---

data/src/main/java/com/semicolon/data/local/dao/UserDao.kt
data/src/main/java/com/semicolon/data/local/database/WalkHubDataBase.kt
data/src/main/java/com/semicolon/data/local/datasource/LocalUserDataSource.kt
data/src/main/java/com/semicolon/data/local/datasource/LocalUserDataSourceImpl.kt
data/src/main/java/com/semicolon/data/local/entity/user/FetchAuthInfoRoomEntity.kt
data/src/main/java/com/semicolon/data/local/entity/user/FetchDailyGoalRoomEntity.kt
data/src/main/java/com/semicolon/data/local/entity/user/FetchInfoRoomEntity.kt
data/src/main/java/com/semicolon/data/local/entity/user/FetchUserHealthRoomEntity.kt
data/src/main/java/com/semicolon/data/local/entity/user/UserMyPageRoomEntity.kt
data/src/main/java/com/semicolon/data/remote/datasource/RemoteUserDataSource.kt
data/src/main/java/com/semicolon/data/remote/datasource/RemoteUserDataSourceImpl.kt
data/src/main/java/com/semicolon/data/remote/response/users/FetchAuthInfoResponse.kt
data/src/main/java/com/semicolon/data/remote/response/users/FetchDailyGoalResponse.kt
data/src/main/java/com/semicolon/data/remote/response/users/FetchInfoResponse.kt
data/src/main/java/com/semicolon/data/remote/response/users/FetchUserHealthResponse.kt
data/src/main/java/com/semicolon/data/repository/UserRepositoryImpl.kt
domain/src/main/java/com/semicolon/domain/entity/users/FetchAuthInfoEntity.kt
domain/src/main/java/com/semicolon/domain/entity/users/FetchDailyGoalEntity.kt
domain/src/main/java/com/semicolon/domain/entity/users/FetchInfoEntity.kt
domain/src/main/java/com/semicolon/domain/entity/users/FetchUserHealthEntity.kt
domain/src/main/java/com/semicolon/domain/repository/UserRepository.kt
domain/src/main/java/com/semicolon/domain/usecase/user/ChangeIndependenceUseCase.kt
domain/src/main/java/com/semicolon/domain/usecase/user/CheckAccountOverlapUseCase.kt
domain/src/main/java/com/semicolon/domain/usecase/user/CheckClassCodeUseCase.kt
domain/src/main/java/com/semicolon/domain/usecase/user/DeleteAccountUseCase.kt
domain/src/main/java/com/semicolon/domain/usecase/user/DeleteClassUseCase.kt
domain/src/main/java/com/semicolon/domain/usecase/user/FetchAuthInfoUseCase.kt
domain/src/main/java/com/semicolon/domain/usecase/user/FetchDailyGoalUseCase.kt
domain/src/main/java/com/semicolon/domain/usecase/user/FetchInfoUseCase.kt
domain/src/main/java/com/semicolon/domain/usecase/user/FetchUserHealthUseCase.kt

> 
user 새로운 기능 추가
domain & data layer 작업

🔀 :: (#328) user 새로운 기능 추가

---

presentation/src/main/AndroidManifest.xml
presentation/src/main/java/com/semicolon/walkhub/ui/profile/setting/SettingActivity.kt
presentation/src/main/java/com/semicolon/walkhub/ui/splash/Splash.kt
presentation/src/main/java/com/semicolon/walkhub/ui/splash/SplashActivity.kt
presentation/src/main/java/com/semicolon/walkhub/viewmodel/splash/SplashViewModel.kt
presentation/src/main/res/values/themes.xml

> splash 구현
- splash 구현
- 자동 로그인 성공 여부에 따른 화면 전환

🔀 :: (#316) splash

---

presentation/src/main/java/com/semicolon/walkhub/ui/home/HomeFragment.kt
presentation/src/main/java/com/semicolon/walkhub/ui/hub/ui/HubSearchSchoolActivity.kt
presentation/src/main/java/com/semicolon/walkhub/ui/profile/ProfileFragment.kt
presentation/src/main/java/com/semicolon/walkhub/ui/profile/setting/SettingActivity.kt
presentation/src/main/java/com/semicolon/walkhub/viewmodel/home/HomeViewModel.kt
presentation/src/main/java/com/semicolon/walkhub/viewmodel/hub/HubSearchSchoolViewModel.kt

그동안 홈 Fragment에서 튕겼던게 서버의 오류인지 제 오류인지 잘 모르겠지만 우리학교 랭킹 받아오기에서 오류가 계속 나는 바람에 일단 이렇게 둘순 없어서 주석처리했습니다. 빠른 시일 내에 해결하겠습니다.
- 
-

🔀 :: (#331) 잔오류들 수정
